[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_sqlite"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "npm ci"]

[phases.build]
cmds = ["npm run build"]

[phases.deploy]
cmds = ["php artisan db:seed --class=AdminSeeder --force"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"